my_string = input('Введите произвольный текст: ')
print('Вы ввели', len(my_string), 'символов')
print('Ваш текст в верхнем регистре:', my_string.upper())
print('Ваш текст в нижнем регистре:', my_string.lower())
print('Ваш текст без пробелов:', my_string.replace(' ', ''))
print('Первый символ который вы ввели:', my_string[0])
print('Последний символ который вы ввели:', my_string[-1])
